### PR TITLE
Fix transposed weights in get_weight

### PR DESCRIPTION
**Pull request by gdalle**
Solves #39

### CODE REVIEW

**Comment by jrklasen** [comment]
Thanks a million. Would it be possible to tag a new release including this fix?

**Comment by jrklasen** [comment]
@gdalle would it be possible to release this fix?

**Comment by gdalle** [comment]
Taking a look this week, sorry

**Comment by gdalle** [comment]
Done https://github.com/JuliaRegistries/General/pull/82541

**Pull request merged**
